name: The-Punisher
author: i54m
website: https://i54m.com
version: ${project.version}
api-version: 1.13
main: com.i54m.punisher.bukkit.PunisherBukkitPlugin
softdepend: [LuckPerms, Votifier, NuVotifier]
description: The Bukkit side of the Punisher plugin.

commands:
  ban:
    description: bans a player.
